### ISSUE TITLE
Color scheme preference doesn't work in flatpak

### ISSUE THREAD

**Issue by baarkerlounger** [ppvan/psequel#52]
Changing the color scheme in preferences doesn't change anything in the UI on v0.1.6 installed from Flathub. It doesn't output any error message either.

**Comment by ppvan** [comment]
Yeah i', plan to remove that's feature. This is because i have current query highlight (with some color). So for each theme i have to choose a suiable color.

Do you think adding for theme is needed? I mean changing only the editor make it out of place personally i did not like theme options, but if you insist then i might do it.

**Comment by ppvan** [comment]
Agreed, will work on it in nextweek
