### ISSUE TITLE
PSequel only shows a single column of data

### ISSUE THREAD

**Issue by Vinnl** [ppvan/psequel#88]
Not sure if this is related to the [recent update](https://github.com/ppvan/psequel/issues/87#issuecomment-2417260547) (I don't think I had this problem back then), but I only see a single column of data for every table:

![image](https://github.com/user-attachments/assets/e6e78a92-2bf5-4c8e-84d0-08bbf0d7def8)

Even when manually running a `SELECT *` query, I only see a single column:

![image](https://github.com/user-attachments/assets/abbd936c-e87e-443d-bfa7-c2101079fd1e)

I do see all the data if running `psql` myself.

```bash
$ flatpak info me.ppvan.psequel

psequel - A minimal SQL client

          ID: me.ppvan.psequel
         Ref: app/me.ppvan.psequel/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.2.0
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 6.5 MB
     Runtime: org.gnome.Platform/x86_64/47
         Sdk: org.gnome.Sdk/x86_64/47

      Commit: 4733dd40dd6df30ac0c7aa8721dceaca24d02b8a9143238410c6a99270471965
      Parent: 3a6038eeed7a66d45a5c129442d4a8097596bdb233793f3b2e190fc847036cc9
     Subject: Update and rename me.ppvan.psequel.json to me.ppvan.psequel.yml (8d0ea12a)
        Date: 2024-10-16 03:36:41 +0000
```

**Comment by illusionist-moon** [comment]
same problem...

**Comment by ppvan** [comment]
@Vinnl @illusionist-moon  working on it...
Seem to be another silly mistake

**Comment by ppvan** [comment]
I think I fixed the problem in https://github.com/flathub/me.ppvan.psequel/commit/4c43756f1697d9bec6cfb3d4bf005018680a0252 . If nothing bad happens, you can get updates in 4-5h from now.

I also set `page size` to 50 to decrease lags when change table in dataview. Since gtk column view(and listview) haves all sort of performance problems like [this one](https://gitlab.gnome.org/GNOME/gtk/-/issues/6409) and [that one](https://gitlab.gnome.org/GNOME/gtk/-/issues/6557). There is no goodway to quickly create 200 * 20 widgets in a short time.

Anyways, thanks for using my app! If you think some features can make it a better app, feel free to file an issue.

**Comment by Vinnl** [comment]
Thank you! It looks a bit different and more dense now, but it's showing all columns, so that fixes this issue.

And to be honest, I'm already very happy with PSequel. #73 would be nice, but I expect that that's quite a bit of work. Other than that it does what I need it to do, but I'll try to keep an eye out for potential improvements.
